filebeat.config.modules:
- enabled: true
  paths:
    - /usr/share/filebeat/modules.d/*.yml

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log
- type: log
  enabled: true
  paths:
    - /home/nginx/*.log
    
#output.logstash:
#  hosts: ["logstash:5044"]
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kib:5601"
