global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'devopslabs'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
#  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'prometheus'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    # and here are the definitions of the explicit targets (if no service discovery is used)
#    static_configs:
#      - targets: ['localhost:9090']
# Load a directory of JSON configs to do an auto-discovery
  - job_name: 'stub'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.json

# Rule files specifies a list of globs. 
# Rules and alerts are read from all matching files.
rule_files:
  - /etc/prometheus/rules/recording_rules/cpu.yml
  - /etc/prometheus/rules/alert_rules/alert_instance_down_example.yml

# Specifies settings related to the Alertmanager.
alerting:
#  alert_relabel_configs:
#    - <relabel_config>
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093'] 

