services:
  postgres-db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data
 
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - postgres-db
    volumes:
      - ./runbooks:/runbooks
      - /tmp/data:/data
